packages:
  - "packages/*"
  - "examples/*"
  - "docs"
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
  rollup: true
  "@rollup/rollup-linux-x64-gnu": true
  "@rollup/rollup-linux-x64-musl": true
  "@rollup/rollup-linux-arm64-gnu": true
  "@rollup/rollup-linux-arm64-musl": true
