import { useEffect, useRef } from 'react';

// Map of font family names to their Google Fonts identifiers (500+ fonts)
const GOOGLE_FONTS: Record<string, string> = {
  // Sans-Serif Fonts (A-Z)
  'Abel': 'Abel',
  'Acme': 'Acme',
  'Advent Pro': 'Advent+Pro:wght@400;500;600;700',
  'Afacad': 'Afacad:wght@400;500;600;700',
  'Alata': 'Alata',
  'Albert Sans': 'Albert+Sans:wght@400;500;600;700',
  'Alegreya Sans': 'Alegreya+Sans:wght@400;500;700',
  'Amaranth': 'Amaranth:wght@400;700',
  'Amiko': 'Amiko:wght@400;600;700',
  'Andika': 'Andika:wght@400;700',
  'Anybody': 'Anybody:wght@400;500;600;700',
  'Antonio': 'Antonio:wght@400;500;600;700',
  'Archivo': 'Archivo:wght@400;500;600;700',
  'Archivo Narrow': 'Archivo+Narrow:wght@400;500;600;700',
  'Arimo': 'Arimo:wght@400;500;600;700',
  'Armata': 'Armata',
  'Arsenal': 'Arsenal:wght@400;700',
  'Asap': 'Asap:wght@400;500;600;700',
  'Asap Condensed': 'Asap+Condensed:wght@400;500;600;700',
  'Assistant': 'Assistant:wght@400;500;600;700',
  'Atkinson Hyperlegible': 'Atkinson+Hyperlegible:wght@400;700',
  'Average Sans': 'Average+Sans',
  'B612': 'B612:wght@400;700',
  'Balsamiq Sans': 'Balsamiq+Sans:wght@400;700',
  'Barlow': 'Barlow:wght@400;500;600;700',
  'Barlow Condensed': 'Barlow+Condensed:wght@400;500;600;700',
  'Barlow Semi Condensed': 'Barlow+Semi+Condensed:wght@400;500;600;700',
  'Basic': 'Basic',
  'Be Vietnam Pro': 'Be+Vietnam+Pro:wght@400;500;600;700',
  'BenchNine': 'BenchNine:wght@400;700',
  'Big Shoulders Display': 'Big+Shoulders+Display:wght@400;500;600;700',
  'Big Shoulders Text': 'Big+Shoulders+Text:wght@400;500;600;700',
  'Blinker': 'Blinker:wght@400;600;700',
  'Bricolage Grotesque': 'Bricolage+Grotesque:wght@400;500;600;700',
  'Cabin': 'Cabin:wght@400;500;600;700',
  'Cabin Condensed': 'Cabin+Condensed:wght@400;500;600;700',
  'Cantarell': 'Cantarell:wght@400;700',
  'Capriola': 'Capriola',
  'Carme': 'Carme',
  'Carrois Gothic': 'Carrois+Gothic',
  'Catamaran': 'Catamaran:wght@400;500;600;700',
  'Chakra Petch': 'Chakra+Petch:wght@400;500;600;700',
  'Changa': 'Changa:wght@400;500;600;700',
  'Chivo': 'Chivo:wght@400;500;600;700',
  'Comfortaa': 'Comfortaa:wght@400;500;600;700',
  'Commissioner': 'Commissioner:wght@400;500;600;700',
  'Convergence': 'Convergence',
  'Cuprum': 'Cuprum:wght@400;500;600;700',
  'Darker Grotesque': 'Darker+Grotesque:wght@400;500;600;700',
  'Didact Gothic': 'Didact+Gothic',
  'DM Sans': 'DM+Sans:wght@400;500;600;700',
  'Dongle': 'Dongle:wght@400;700',
  'Doppio One': 'Doppio+One',
  'Dosis': 'Dosis:wght@400;500;600;700',
  'Economica': 'Economica:wght@400;700',
  'El Messiri': 'El+Messiri:wght@400;500;600;700',
  'Electrolize': 'Electrolize',
  'Encode Sans': 'Encode+Sans:wght@400;500;600;700',
  'Encode Sans Condensed': 'Encode+Sans+Condensed:wght@400;500;600;700',
  'Encode Sans Expanded': 'Encode+Sans+Expanded:wght@400;500;600;700',
  'Epilogue': 'Epilogue:wght@400;500;600;700',
  'Exo': 'Exo:wght@400;500;600;700',
  'Exo 2': 'Exo+2:wght@400;500;600;700',
  'Expletus Sans': 'Expletus+Sans:wght@400;500;600;700',
  'Fahkwang': 'Fahkwang:wght@400;500;600;700',
  'Familjen Grotesk': 'Familjen+Grotesk:wght@400;500;600;700',
  'Figtree': 'Figtree:wght@400;500;600;700',
  'Fira Sans': 'Fira+Sans:wght@400;500;600;700',
  'Fira Sans Condensed': 'Fira+Sans+Condensed:wght@400;500;600;700',
  'Francois One': 'Francois+One',
  'Fredoka': 'Fredoka:wght@400;500;600;700',
  'Funnel Display': 'Funnel+Display:wght@400;500;600;700',
  'Funnel Sans': 'Funnel+Sans:wght@400;500;600;700',
  'Gabarito': 'Gabarito:wght@400;500;600;700',
  'Geist': 'Geist:wght@400;500;600;700',
  'Geologica': 'Geologica:wght@400;500;600;700',
  'Glory': 'Glory:wght@400;500;600;700',
  'Gothic A1': 'Gothic+A1:wght@400;500;600;700',
  'Gudea': 'Gudea:wght@400;700',
  'Hammersmith One': 'Hammersmith+One',
  'Hanken Grotesk': 'Hanken+Grotesk:wght@400;500;600;700',
  'Heebo': 'Heebo:wght@400;500;600;700',
  'Hind': 'Hind:wght@400;500;600;700',
  'Hind Guntur': 'Hind+Guntur:wght@400;500;600;700',
  'Hind Madurai': 'Hind+Madurai:wght@400;500;600;700',
  'Hind Siliguri': 'Hind+Siliguri:wght@400;500;600;700',
  'Hind Vadodara': 'Hind+Vadodara:wght@400;500;600;700',
  'Homenaje': 'Homenaje',
  'IBM Plex Sans': 'IBM+Plex+Sans:wght@400;500;600;700',
  'IBM Plex Sans Condensed': 'IBM+Plex+Sans+Condensed:wght@400;500;600;700',
  'Inria Sans': 'Inria+Sans:wght@400;700',
  'Instrument Sans': 'Instrument+Sans:wght@400;500;600;700',
  'Inter': 'Inter:wght@400;500;600;700',
  'Inter Tight': 'Inter+Tight:wght@400;500;600;700',
  'Istok Web': 'Istok+Web:wght@400;700',
  'Jaldi': 'Jaldi:wght@400;700',
  'Jockey One': 'Jockey+One',
  'Josefin Sans': 'Josefin+Sans:wght@400;500;600;700',
  'Jost': 'Jost:wght@400;500;600;700',
  'Julius Sans One': 'Julius+Sans+One',
  'Jura': 'Jura:wght@400;500;600;700',
  'K2D': 'K2D:wght@400;500;600;700',
  'Kanit': 'Kanit:wght@400;500;600;700',
  'Kantumruy Pro': 'Kantumruy+Pro:wght@400;500;600;700',
  'Karla': 'Karla:wght@400;500;600;700',
  'Khand': 'Khand:wght@400;500;600;700',
  'Khula': 'Khula:wght@400;600;700',
  'KoHo': 'KoHo:wght@400;500;600;700',
  'Kodchasan': 'Kodchasan:wght@400;500;600;700',
  'Krub': 'Krub:wght@400;500;600;700',
  'Kufam': 'Kufam:wght@400;500;600;700',
  'Kulim Park': 'Kulim+Park:wght@400;600;700',
  'Kumbh Sans': 'Kumbh+Sans:wght@400;500;600;700',
  'Lato': 'Lato:wght@400;700',
  'League Spartan': 'League+Spartan:wght@400;500;600;700',
  'Lexend': 'Lexend:wght@400;500;600;700',
  'Lexend Deca': 'Lexend+Deca:wght@400;500;600;700',
  'Libre Franklin': 'Libre+Franklin:wght@400;500;600;700',
  'Livvic': 'Livvic:wght@400;500;600;700',
  'Mada': 'Mada:wght@400;500;600;700',
  'Magra': 'Magra:wght@400;700',
  'Mali': 'Mali:wght@400;500;600;700',
  'Manjari': 'Manjari:wght@400;700',
  'Manrope': 'Manrope:wght@400;500;600;700;800',
  'Martel Sans': 'Martel+Sans:wght@400;600;700',
  'Marvel': 'Marvel:wght@400;700',
  'Maven Pro': 'Maven+Pro:wght@400;500;600;700',
  'Metrophobic': 'Metrophobic',
  'Mina': 'Mina:wght@400;700',
  'Mitr': 'Mitr:wght@400;500;600;700',
  'Mohave': 'Mohave:wght@400;500;600;700',
  'Monda': 'Monda:wght@400;700',
  'Montserrat': 'Montserrat:wght@400;500;600;700',
  'Mouse Memoirs': 'Mouse+Memoirs',
  'Mukta': 'Mukta:wght@400;500;600;700',
  'Mukta Mahee': 'Mukta+Mahee:wght@400;500;600;700',
  'Mukta Malar': 'Mukta+Malar:wght@400;500;600;700',
  'Mukta Vaani': 'Mukta+Vaani:wght@400;500;600;700',
  'Mulish': 'Mulish:wght@400;500;600;700',
  'Murecho': 'Murecho:wght@400;500;600;700',
  'News Cycle': 'News+Cycle:wght@400;700',
  'Niramit': 'Niramit:wght@400;500;600;700',
  'Nobile': 'Nobile:wght@400;500;700',
  'Noto Sans': 'Noto+Sans:wght@400;500;600;700',
  'Noto Sans Display': 'Noto+Sans+Display:wght@400;500;600;700',
  'Numans': 'Numans',
  'Nunito': 'Nunito:wght@400;500;600;700',
  'Nunito Sans': 'Nunito+Sans:wght@400;500;600;700',
  'Offside': 'Offside',
  'Onest': 'Onest:wght@400;500;600;700',
  'Open Sans': 'Open+Sans:wght@400;500;600;700',
  'Orienta': 'Orienta',
  'Outfit': 'Outfit:wght@400;500;600;700',
  'Overlock': 'Overlock:wght@400;700',
  'Overpass': 'Overpass:wght@400;500;600;700',
  'Oxanium': 'Oxanium:wght@400;500;600;700',
  'Oxygen': 'Oxygen:wght@400;700',
  'Palanquin': 'Palanquin:wght@400;500;600;700',
  'Palanquin Dark': 'Palanquin+Dark:wght@400;500;600;700',
  'Pangolin': 'Pangolin',
  'Pathway Extreme': 'Pathway+Extreme:wght@400;500;600;700',
  'Pathway Gothic One': 'Pathway+Gothic+One',
  'Pattaya': 'Pattaya',
  'Pavanam': 'Pavanam',
  'Philosopher': 'Philosopher:wght@400;700',
  'Play': 'Play:wght@400;700',
  'Plus Jakarta Sans': 'Plus+Jakarta+Sans:wght@400;500;600;700',
  'Pontano Sans': 'Pontano+Sans:wght@400;500;600;700',
  'Poppins': 'Poppins:wght@400;500;600;700',
  'Pragati Narrow': 'Pragati+Narrow:wght@400;700',
  'Pridi': 'Pridi:wght@400;500;600;700',
  'Prompt': 'Prompt:wght@400;500;600;700',
  'Proza Libre': 'Proza+Libre:wght@400;500;600;700',
  'PT Sans': 'PT+Sans:wght@400;700',
  'PT Sans Caption': 'PT+Sans+Caption:wght@400;700',
  'PT Sans Narrow': 'PT+Sans+Narrow:wght@400;700',
  'Public Sans': 'Public+Sans:wght@400;500;600;700',
  'Puritan': 'Puritan:wght@400;700',
  'Quantico': 'Quantico:wght@400;700',
  'Quattrocento Sans': 'Quattrocento+Sans:wght@400;700',
  'Questrial': 'Questrial',
  'Quicksand': 'Quicksand:wght@400;500;600;700',
  'Radio Canada': 'Radio+Canada:wght@400;500;600;700',
  'Rajdhani': 'Rajdhani:wght@400;500;600;700',
  'Raleway': 'Raleway:wght@400;500;600;700',
  'Rambla': 'Rambla:wght@400;700',
  'Rationale': 'Rationale',
  'Readex Pro': 'Readex+Pro:wght@400;500;600;700',
  'Red Hat Display': 'Red+Hat+Display:wght@400;500;600;700',
  'Red Hat Text': 'Red+Hat+Text:wght@400;500;600;700',
  'Roboto': 'Roboto:wght@400;500;700',
  'Roboto Condensed': 'Roboto+Condensed:wght@400;500;700',
  'Roboto Flex': 'Roboto+Flex:wght@400;500;600;700',
  'Ropa Sans': 'Ropa+Sans:wght@400',
  'Rosario': 'Rosario:wght@400;500;600;700',
  'Rubik': 'Rubik:wght@400;500;600;700',
  'Ruda': 'Ruda:wght@400;500;600;700',
  'Ruluko': 'Ruluko',
  'Saira': 'Saira:wght@400;500;600;700',
  'Saira Condensed': 'Saira+Condensed:wght@400;500;600;700',
  'Saira Extra Condensed': 'Saira+Extra+Condensed:wght@400;500;600;700',
  'Saira Semi Condensed': 'Saira+Semi+Condensed:wght@400;500;600;700',
  'Sarabun': 'Sarabun:wght@400;500;600;700',
  'Sarala': 'Sarala:wght@400;700',
  'Sarpanch': 'Sarpanch:wght@400;500;600;700',
  'Scada': 'Scada:wght@400;700',
  'Schibsted Grotesk': 'Schibsted+Grotesk:wght@400;500;600;700',
  'Secular One': 'Secular+One',
  'Sen': 'Sen:wght@400;500;600;700',
  'Shanti': 'Shanti',
  'Share': 'Share:wght@400;700',
  'Share Tech': 'Share+Tech',
  'Signika': 'Signika:wght@400;500;600;700',
  'Signika Negative': 'Signika+Negative:wght@400;500;600;700',
  'Sintony': 'Sintony:wght@400;700',
  'Six Caps': 'Six+Caps',
  'Smooch Sans': 'Smooch+Sans:wght@400;500;600;700',
  'Sofia Sans': 'Sofia+Sans:wght@400;500;600;700',
  'Sofia Sans Condensed': 'Sofia+Sans+Condensed:wght@400;500;600;700',
  'Solway': 'Solway:wght@400;500;700',
  'Sono': 'Sono:wght@400;500;600;700',
  'Sora': 'Sora:wght@400;500;600;700',
  'Source Sans Pro': 'Source+Sans+Pro:wght@400;600;700',
  'Source Sans 3': 'Source+Sans+3:wght@400;500;600;700',
  'Space Grotesk': 'Space+Grotesk:wght@400;500;600;700',
  'Spinnaker': 'Spinnaker',
  'Spline Sans': 'Spline+Sans:wght@400;500;600;700',
  'Strait': 'Strait',
  'Sulphur Point': 'Sulphur+Point:wght@400;700',
  'Syne': 'Syne:wght@400;500;600;700',
  'Tajawal': 'Tajawal:wght@400;500;700',
  'Tauri': 'Tauri',
  'Taviraj': 'Taviraj:wght@400;500;600;700',
  'Teko': 'Teko:wght@400;500;600;700',
  'Telex': 'Telex',
  'Tenor Sans': 'Tenor+Sans',
  'Text Me One': 'Text+Me+One',
  'Thasadith': 'Thasadith:wght@400;700',
  'Titillium Web': 'Titillium+Web:wght@400;600;700',
  'Tomorrow': 'Tomorrow:wght@400;500;600;700',
  'Trispace': 'Trispace:wght@400;500;600;700',
  'Truculenta': 'Truculenta:wght@400;500;600;700',
  'Turret Road': 'Turret+Road:wght@400;500;700',
  'Ubuntu': 'Ubuntu:wght@400;500;700',
  'Ubuntu Condensed': 'Ubuntu+Condensed',
  'Unbounded': 'Unbounded:wght@400;500;600;700',
  'Unica One': 'Unica+One',
  'Urbanist': 'Urbanist:wght@400;500;600;700',
  'Varela': 'Varela',
  'Varela Round': 'Varela+Round',
  'Varta': 'Varta:wght@400;500;600;700',
  'Vazirmatn': 'Vazirmatn:wght@400;500;600;700',
  'Viga': 'Viga',
  'Voltaire': 'Voltaire',
  'Wire One': 'Wire+One',
  'Wix Madefor Display': 'Wix+Madefor+Display:wght@400;500;600;700',
  'Wix Madefor Text': 'Wix+Madefor+Text:wght@400;500;600;700',
  'Work Sans': 'Work+Sans:wght@400;500;600;700',
  'Yaldevi': 'Yaldevi:wght@400;500;600;700',
  'Yantramanav': 'Yantramanav:wght@400;500;700',
  // Serif Fonts
  'Aleo': 'Aleo:wght@400;500;600;700',
  'Alice': 'Alice',
  'Antic Slab': 'Antic+Slab',
  'Arvo': 'Arvo:wght@400;700',
  'BioRhyme': 'BioRhyme:wght@400;700',
  'Bitter': 'Bitter:wght@400;500;600;700',
  'Bree Serif': 'Bree+Serif',
  'Cantata One': 'Cantata+One',
  'Cardo': 'Cardo:wght@400;700',
  'Caudex': 'Caudex:wght@400;700',
  'Copse': 'Copse',
  'Corben': 'Corben:wght@400;700',
  'Cormorant': 'Cormorant:wght@400;500;600;700',
  'Cormorant Garamond': 'Cormorant+Garamond:wght@400;500;600;700',
  'Crete Round': 'Crete+Round:wght@400',
  'Crimson Pro': 'Crimson+Pro:wght@400;500;600;700',
  'Crimson Text': 'Crimson+Text:wght@400;600;700',
  'DM Serif Display': 'DM+Serif+Display',
  'DM Serif Text': 'DM+Serif+Text',
  'Domine': 'Domine:wght@400;500;600;700',
  'EB Garamond': 'EB+Garamond:wght@400;500;600;700',
  'Eczar': 'Eczar:wght@400;500;600;700',
  'Enriqueta': 'Enriqueta:wght@400;500;600;700',
  'Faustina': 'Faustina:wght@400;500;600;700',
  'Frank Ruhl Libre': 'Frank+Ruhl+Libre:wght@400;500;600;700',
  'Fraunces': 'Fraunces:wght@400;500;600;700',
  'Gelasio': 'Gelasio:wght@400;500;600;700',
  'Gentium Plus': 'Gentium+Plus:wght@400;700',
  'Gilda Display': 'Gilda+Display',
  'Glegoo': 'Glegoo:wght@400;700',
  'Halant': 'Halant:wght@400;500;600;700',
  'Headland One': 'Headland+One',
  'Hepta Slab': 'Hepta+Slab:wght@400;500;600;700',
  'IBM Plex Serif': 'IBM+Plex+Serif:wght@400;500;600;700',
  'Ibarra Real Nova': 'Ibarra+Real+Nova:wght@400;500;600;700',
  'Inika': 'Inika:wght@400;700',
  'Inknut Antiqua': 'Inknut+Antiqua:wght@400;500;600;700',
  'Inria Serif': 'Inria+Serif:wght@400;700',
  'Italiana': 'Italiana',
  'Josefin Slab': 'Josefin+Slab:wght@400;500;600;700',
  'Judson': 'Judson:wght@400;700',
  'Junge': 'Junge',
  'Kameron': 'Kameron:wght@400;700',
  'Karma': 'Karma:wght@400;500;600;700',
  'Kreon': 'Kreon:wght@400;500;600;700',
  'Kurale': 'Kurale',
  'Laila': 'Laila:wght@400;500;600;700',
  'Ledger': 'Ledger',
  'Libre Baskerville': 'Libre+Baskerville:wght@400;700',
  'Libre Bodoni': 'Libre+Bodoni:wght@400;500;600;700',
  'Libre Caslon Text': 'Libre+Caslon+Text:wght@400;700',
  'Linden Hill': 'Linden+Hill:wght@400',
  'Literata': 'Literata:wght@400;500;600;700',
  'Lora': 'Lora:wght@400;500;600;700',
  'Lusitana': 'Lusitana:wght@400;700',
  'Lustria': 'Lustria',
  'Maitree': 'Maitree:wght@400;500;600;700',
  'Manuale': 'Manuale:wght@400;500;600;700',
  'Marcellus': 'Marcellus',
  'Markazi Text': 'Markazi+Text:wght@400;500;600;700',
  'Martel': 'Martel:wght@400;600;700',
  'Mate': 'Mate:wght@400',
  'Merriweather': 'Merriweather:wght@400;700',
  'Montagu Slab': 'Montagu+Slab:wght@400;500;600;700',
  'Neuton': 'Neuton:wght@400;700',
  'Newsreader': 'Newsreader:wght@400;500;600;700',
  'Noticia Text': 'Noticia+Text:wght@400;700',
  'Noto Serif': 'Noto+Serif:wght@400;500;600;700',
  'Old Standard TT': 'Old+Standard+TT:wght@400;700',
  'Oranienbaum': 'Oranienbaum',
  'Ovo': 'Ovo',
  'Petrona': 'Petrona:wght@400;500;600;700',
  'Piazzolla': 'Piazzolla:wght@400;500;600;700',
  'Playfair Display': 'Playfair+Display:wght@400;500;600;700',
  'Playfair Display SC': 'Playfair+Display+SC:wght@400;700',
  'Podkova': 'Podkova:wght@400;500;600;700',
  'Poly': 'Poly:wght@400',
  'Prata': 'Prata',
  'Prociono': 'Prociono',
  'PT Serif': 'PT+Serif:wght@400;700',
  'PT Serif Caption': 'PT+Serif+Caption:wght@400',
  'Quattrocento': 'Quattrocento:wght@400;700',
  'Radley': 'Radley:wght@400',
  'Rasa': 'Rasa:wght@400;500;600;700',
  'Roboto Slab': 'Roboto+Slab:wght@400;500;600;700',
  'Roboto Serif': 'Roboto+Serif:wght@400;500;600;700',
  'Rokkitt': 'Rokkitt:wght@400;500;600;700',
  'Rosarivo': 'Rosarivo:wght@400',
  'Rozha One': 'Rozha+One',
  'Rufina': 'Rufina:wght@400;700',
  'Sahitya': 'Sahitya:wght@400;700',
  'Sanchez': 'Sanchez:wght@400',
  'Scope One': 'Scope+One',
  'Slabo 27px': 'Slabo+27px',
  'Sorts Mill Goudy': 'Sorts+Mill+Goudy:wght@400',
  'Source Serif Pro': 'Source+Serif+Pro:wght@400;600;700',
  'Source Serif 4': 'Source+Serif+4:wght@400;500;600;700',
  'Spectral': 'Spectral:wght@400;500;600;700',
  'STIX Two Text': 'STIX+Two+Text:wght@400;500;600;700',
  'Stoke': 'Stoke:wght@400',
  'Suez One': 'Suez+One',
  'Sumana': 'Sumana:wght@400;700',
  'Sura': 'Sura:wght@400;700',
  'Suranna': 'Suranna',
  'Texturina': 'Texturina:wght@400;500;600;700',
  'Tienne': 'Tienne:wght@400;700',
  'Tillana': 'Tillana:wght@400;500;600;700',
  'Tinos': 'Tinos:wght@400;700',
  'Trirong': 'Trirong:wght@400;500;600;700',
  'Trocchi': 'Trocchi',
  'Trykker': 'Trykker',
  'Unna': 'Unna:wght@400;700',
  'Vesper Libre': 'Vesper+Libre:wght@400;500;700',
  'Viaoda Libre': 'Viaoda+Libre',
  'Vidaloka': 'Vidaloka',
  'Volkhov': 'Volkhov:wght@400;700',
  'Vollkorn': 'Vollkorn:wght@400;500;600;700',
  'Yeseva One': 'Yeseva+One',
  'Yrsa': 'Yrsa:wght@400;500;600;700',
  'Zilla Slab': 'Zilla+Slab:wght@400;500;600;700',
  // Display Fonts
  'Alfa Slab One': 'Alfa+Slab+One',
  'Anton': 'Anton',
  'Archivo Black': 'Archivo+Black',
  'Audiowide': 'Audiowide',
  'Bangers': 'Bangers',
  'Bebas Neue': 'Bebas+Neue',
  'Black Ops One': 'Black+Ops+One',
  'Bowlby One SC': 'Bowlby+One+SC',
  'Bungee': 'Bungee',
  'Calistoga': 'Calistoga',
  'Carter One': 'Carter+One',
  'Changa One': 'Changa+One',
  'Cinzel': 'Cinzel:wght@400;500;600;700',
  'Cinzel Decorative': 'Cinzel+Decorative:wght@400;700',
  'Concert One': 'Concert+One',
  'Contrail One': 'Contrail+One',
  'Fjalla One': 'Fjalla+One',
  'Fredericka the Great': 'Fredericka+the+Great',
  'Fugaz One': 'Fugaz+One',
  'Graduate': 'Graduate',
  'Gravitas One': 'Gravitas+One',
  'Holtwood One SC': 'Holtwood+One+SC',
  'Kelly Slab': 'Kelly+Slab',
  'Knewave': 'Knewave',
  'Krona One': 'Krona+One',
  'League Gothic': 'League+Gothic',
  'Leckerli One': 'Leckerli+One',
  'Lilita One': 'Lilita+One',
  'Limelight': 'Limelight',
  'Lobster': 'Lobster',
  'Lobster Two': 'Lobster+Two:wght@400;700',
  'Luckiest Guy': 'Luckiest+Guy',
  'Megrim': 'Megrim',
  'Michroma': 'Michroma',
  'Modak': 'Modak',
  'Monoton': 'Monoton',
  'MuseoModerno': 'MuseoModerno:wght@400;500;600;700',
  'Oleo Script': 'Oleo+Script:wght@400;700',
  'Orbitron': 'Orbitron:wght@400;500;600;700',
  'Original Surfer': 'Original+Surfer',
  'Oswald': 'Oswald:wght@400;500;600;700',
  'Pacifico': 'Pacifico',
  'Passion One': 'Passion+One:wght@400;700',
  'Patua One': 'Patua+One',
  'Paytone One': 'Paytone+One',
  'Permanent Marker': 'Permanent+Marker',
  'Pirata One': 'Pirata+One',
  'Playball': 'Playball',
  'Poiret One': 'Poiret+One',
  'Poller One': 'Poller+One',
  'Press Start 2P': 'Press+Start+2P',
  'Racing Sans One': 'Racing+Sans+One',
  'Rammetto One': 'Rammetto+One',
  'Ranchers': 'Ranchers',
  'Righteous': 'Righteous',
  'Rowdies': 'Rowdies:wght@400;700',
  'Russo One': 'Russo+One',
  'Rye': 'Rye',
  'Sancreek': 'Sancreek',
  'Shojumaru': 'Shojumaru',
  'Shrikhand': 'Shrikhand',
  'Sigmar One': 'Sigmar+One',
  'Skranji': 'Skranji:wght@400;700',
  'Slackey': 'Slackey',
  'Special Elite': 'Special+Elite',
  'Spicy Rice': 'Spicy+Rice',
  'Squada One': 'Squada+One',
  'Staatliches': 'Staatliches',
  'Stalinist One': 'Stalinist+One',
  'Stardos Stencil': 'Stardos+Stencil:wght@400;700',
  'Titan One': 'Titan+One',
  'Trade Winds': 'Trade+Winds',
  'Ultra': 'Ultra',
  'Vast Shadow': 'Vast+Shadow',
  'Wallpoet': 'Wallpoet',
  'Warnes': 'Warnes',
  'Wellfleet': 'Wellfleet',
  'Yanone Kaffeesatz': 'Yanone+Kaffeesatz:wght@400;500;600;700',
  // Handwriting Fonts
  'Amatic SC': 'Amatic+SC:wght@400;700',
  'Alex Brush': 'Alex+Brush',
  'Allura': 'Allura',
  'Bad Script': 'Bad+Script',
  'Berkshire Swash': 'Berkshire+Swash',
  'Bilbo Swash Caps': 'Bilbo+Swash+Caps',
  'Caveat': 'Caveat:wght@400;500;600;700',
  'Cedarville Cursive': 'Cedarville+Cursive',
  'Clicker Script': 'Clicker+Script',
  'Cookie': 'Cookie',
  'Courgette': 'Courgette',
  'Damion': 'Damion',
  'Dancing Script': 'Dancing+Script:wght@400;500;600;700',
  'Dawning of a New Day': 'Dawning+of+a+New+Day',
  'Delius': 'Delius',
  'Euphoria Script': 'Euphoria+Script',
  'Gloria Hallelujah': 'Gloria+Hallelujah',
  'Gochi Hand': 'Gochi+Hand',
  'Grand Hotel': 'Grand+Hotel',
  'Great Vibes': 'Great+Vibes',
  'Handlee': 'Handlee',
  'Homemade Apple': 'Homemade+Apple',
  'Indie Flower': 'Indie+Flower',
  'Itim': 'Itim',
  'Kalam': 'Kalam:wght@400;700',
  'Kaushan Script': 'Kaushan+Script',
  'Kristi': 'Kristi',
  'La Belle Aurore': 'La+Belle+Aurore',
  'Marck Script': 'Marck+Script',
  'Merienda': 'Merienda:wght@400;500;600;700',
  'Mr Dafoe': 'Mr+Dafoe',
  'Neucha': 'Neucha',
  'Niconne': 'Niconne',
  'Nothing You Could Do': 'Nothing+You+Could+Do',
  'Over the Rainbow': 'Over+the+Rainbow',
  'Parisienne': 'Parisienne',
  'Patrick Hand': 'Patrick+Hand',
  'Petit Formal Script': 'Petit+Formal+Script',
  'Pinyon Script': 'Pinyon+Script',
  'Rancho': 'Rancho',
  'Reenie Beanie': 'Reenie+Beanie',
  'Rochester': 'Rochester',
  'Rock Salt': 'Rock+Salt',
  'Rouge Script': 'Rouge+Script',
  'Sacramento': 'Sacramento',
  'Satisfy': 'Satisfy',
  'Schoolbell': 'Schoolbell',
  'Shadows Into Light': 'Shadows+Into+Light',
  'Short Stack': 'Short+Stack',
  'Sue Ellen Francisco': 'Sue+Ellen+Francisco',
  'Tangerine': 'Tangerine:wght@400;700',
  'Waiting for the Sunrise': 'Waiting+for+the+Sunrise',
  'Walter Turncoat': 'Walter+Turncoat',
  'Yellowtail': 'Yellowtail',
  'Yesteryear': 'Yesteryear',
  'Zeyada': 'Zeyada',
  // Monospace Fonts
  'Anonymous Pro': 'Anonymous+Pro:wght@400;700',
  'Azeret Mono': 'Azeret+Mono:wght@400;500;600;700',
  'B612 Mono': 'B612+Mono:wght@400;700',
  'Courier Prime': 'Courier+Prime:wght@400;700',
  'Cousine': 'Cousine:wght@400;700',
  'Cutive Mono': 'Cutive+Mono',
  'DM Mono': 'DM+Mono:wght@400;500',
  'Fira Code': 'Fira+Code:wght@400;500;600;700',
  'Fira Mono': 'Fira+Mono:wght@400;500;700',
  'Geist Mono': 'Geist+Mono:wght@400;500;600;700',
  'IBM Plex Mono': 'IBM+Plex+Mono:wght@400;500;600;700',
  'Inconsolata': 'Inconsolata:wght@400;500;600;700',
  'JetBrains Mono': 'JetBrains+Mono:wght@400;500;600;700',
  'Major Mono Display': 'Major+Mono+Display',
  'Noto Sans Mono': 'Noto+Sans+Mono:wght@400;500;600;700',
  'Nova Mono': 'Nova+Mono',
  'Overpass Mono': 'Overpass+Mono:wght@400;500;600;700',
  'Oxygen Mono': 'Oxygen+Mono',
  'PT Mono': 'PT+Mono',
  'Red Hat Mono': 'Red+Hat+Mono:wght@400;500;600;700',
  'Roboto Mono': 'Roboto+Mono:wght@400;500;600;700',
  'Share Tech Mono': 'Share+Tech+Mono',
  'Source Code Pro': 'Source+Code+Pro:wght@400;500;600;700',
  'Space Mono': 'Space+Mono:wght@400;700',
  'Spline Sans Mono': 'Spline+Sans+Mono:wght@400;500;600;700',
  'Syne Mono': 'Syne+Mono',
  'Ubuntu Mono': 'Ubuntu+Mono:wght@400;700',
  'VT323': 'VT323',
  'Xanh Mono': 'Xanh+Mono:wght@400',
  // Additional Unique Fonts
  'Abril Fatface': 'Abril+Fatface',
  'Adamina': 'Adamina',
  'Aguafina Script': 'Aguafina+Script',
  'Akronim': 'Akronim',
  'Aladin': 'Aladin',
  'Aldrich': 'Aldrich',
  'Alegreya': 'Alegreya:wght@400;500;600;700',
  'Alegreya SC': 'Alegreya+SC:wght@400;500;700',
  'Alike': 'Alike',
  'Alike Angular': 'Alike+Angular',
  'Allan': 'Allan:wght@400;700',
  'Allison': 'Allison',
  'Almendra': 'Almendra:wght@400;700',
  'Almendra Display': 'Almendra+Display',
  'Almendra SC': 'Almendra+SC',
  'Amarante': 'Amarante',
  'Amethysta': 'Amethysta',
  'Amiri': 'Amiri:wght@400;700',
  'Amita': 'Amita:wght@400;700',
  'Anaheim': 'Anaheim',
  'Andada Pro': 'Andada+Pro:wght@400;500;600;700',
  'Angkor': 'Angkor',
  'Annie Use Your Telescope': 'Annie+Use+Your+Telescope',
  'Antic': 'Antic',
  'Antic Didone': 'Antic+Didone',
  'Arapey': 'Arapey:wght@400',
  'Arbutus': 'Arbutus',
  'Arbutus Slab': 'Arbutus+Slab',
  'Architects Daughter': 'Architects+Daughter',
  'Aref Ruqaa': 'Aref+Ruqaa:wght@400;700',
  'Arima Madurai': 'Arima+Madurai:wght@400;500;700',
  'Arizonia': 'Arizonia',
  'Artifika': 'Artifika',
  'Arya': 'Arya:wght@400;700',
  'Asul': 'Asul:wght@400;700',
  'Athiti': 'Athiti:wght@400;500;600;700',
  'Atma': 'Atma:wght@400;500;600;700',
  'Atomic Age': 'Atomic+Age',
  'Aubrey': 'Aubrey',
  'Autour One': 'Autour+One',
  'Average': 'Average',
  'Averia Gruesa Libre': 'Averia+Gruesa+Libre',
  'Averia Libre': 'Averia+Libre:wght@400;700',
  'Averia Sans Libre': 'Averia+Sans+Libre:wght@400;700',
  'Averia Serif Libre': 'Averia+Serif+Libre:wght@400;700',
  'Babylonica': 'Babylonica',
  'Bacasime Antique': 'Bacasime+Antique',
  'Bahiana': 'Bahiana',
  'Bahianita': 'Bahianita',
  'Bai Jamjuree': 'Bai+Jamjuree:wght@400;500;600;700',
  'Ballet': 'Ballet',
  'Baloo 2': 'Baloo+2:wght@400;500;600;700',
  'Baloo Bhai 2': 'Baloo+Bhai+2:wght@400;500;600;700',
  'Baloo Bhaina 2': 'Baloo+Bhaina+2:wght@400;500;600;700',
  'Baloo Chettan 2': 'Baloo+Chettan+2:wght@400;500;600;700',
  'Baloo Da 2': 'Baloo+Da+2:wght@400;500;600;700',
  'Baloo Paaji 2': 'Baloo+Paaji+2:wght@400;500;600;700',
  'Baloo Tamma 2': 'Baloo+Tamma+2:wght@400;500;600;700',
  'Baloo Tammudu 2': 'Baloo+Tammudu+2:wght@400;500;600;700',
  'Baloo Thambi 2': 'Baloo+Thambi+2:wght@400;500;600;700',
  'Balthazar': 'Balthazar',
  'Baskervville': 'Baskervville:wght@400',
  'Battambang': 'Battambang:wght@400;700',
  'Baumans': 'Baumans',
  'Bayon': 'Bayon',
  'Beau Rivage': 'Beau+Rivage',
  'Belgrano': 'Belgrano',
  'Bellefair': 'Bellefair',
  'Belleza': 'Belleza',
  'Bellota': 'Bellota:wght@400;700',
  'Bellota Text': 'Bellota+Text:wght@400;700',
  'Benne': 'Benne',
  'Bentham': 'Bentham',
  'Besley': 'Besley:wght@400;500;600;700',
  'Beth Ellen': 'Beth+Ellen',
  'Bevan': 'Bevan:wght@400',
  'BhuTuka Expanded One': 'BhuTuka+Expanded+One',
  'Big Shoulders Inline Display': 'Big+Shoulders+Inline+Display:wght@400;500;600;700',
  'Big Shoulders Inline Text': 'Big+Shoulders+Inline+Text:wght@400;500;600;700',
  'Big Shoulders Stencil Display': 'Big+Shoulders+Stencil+Display:wght@400;500;600;700',
  'Big Shoulders Stencil Text': 'Big+Shoulders+Stencil+Text:wght@400;500;600;700',
  'Bigelow Rules': 'Bigelow+Rules',
  'Bigshot One': 'Bigshot+One',
  'Bilbo': 'Bilbo',
  'Birthstone': 'Birthstone',
  'Birthstone Bounce': 'Birthstone+Bounce:wght@400;500',
  'Biryani': 'Biryani:wght@400;600;700',
  'Blaka': 'Blaka',
  'Blaka Hollow': 'Blaka+Hollow',
  'Blaka Ink': 'Blaka+Ink',
  'Bodoni Moda': 'Bodoni+Moda:wght@400;500;600;700',
  'Bokor': 'Bokor',
  'Bona Nova': 'Bona+Nova:wght@400;700',
  'Bonbon': 'Bonbon',
  'Bonheur Royale': 'Bonheur+Royale',
  'Boogaloo': 'Boogaloo',
  'Borel': 'Borel',
  'Bowlby One': 'Bowlby+One',
  'Braah One': 'Braah+One',
  'Brawler': 'Brawler:wght@400;700',
  'Bruno Ace': 'Bruno+Ace',
  'Bruno Ace SC': 'Bruno+Ace+SC',
  'Brygada 1918': 'Brygada+1918:wght@400;500;600;700',
  'Bubblegum Sans': 'Bubblegum+Sans',
  'Bubbler One': 'Bubbler+One',
  'Buda': 'Buda:wght@300',
  'Buenard': 'Buenard:wght@400;700',
  'Bungee Hairline': 'Bungee+Hairline',
  'Bungee Outline': 'Bungee+Outline',
  'Bungee Spice': 'Bungee+Spice',
  'Butcherman': 'Butcherman',
  'Butterfly Kids': 'Butterfly+Kids',
  'Cabin Sketch': 'Cabin+Sketch:wght@400;700',
  'Caesar Dressing': 'Caesar+Dressing',
  'Cagliostro': 'Cagliostro',
  'Cairo': 'Cairo:wght@400;500;600;700',
  'Cairo Play': 'Cairo+Play:wght@400;500;600;700',
  'Caladea': 'Caladea:wght@400;700',
  'Calligraffitti': 'Calligraffitti',
  'Cambay': 'Cambay:wght@400;700',
  'Cambo': 'Cambo',
  'Candal': 'Candal',
  'Cantora One': 'Cantora+One',
  'Carattere': 'Carattere',
  'Carlito': 'Carlito:wght@400;700',
  'Carrois Gothic SC': 'Carrois+Gothic+SC',
  'Castoro Titling': 'Castoro+Titling',
  'Ceviche One': 'Ceviche+One',
  'Chango': 'Chango',
  'Charm': 'Charm:wght@400;700',
  'Charmonman': 'Charmonman:wght@400;700',
  'Chathura': 'Chathura:wght@400;700',
  'Chau Philomene One': 'Chau+Philomene+One',
  'Chela One': 'Chela+One',
  'Chelsea Market': 'Chelsea+Market',
  'Chenla': 'Chenla',
  'Cherry Cream Soda': 'Cherry+Cream+Soda',
  'Cherry Swash': 'Cherry+Swash:wght@400;700',
  'Chewy': 'Chewy',
  'Chicle': 'Chicle',
  'Chilanka': 'Chilanka',
  'Chonburi': 'Chonburi',
  'Climate Crisis': 'Climate+Crisis',
  'Coda': 'Coda:wght@400',
  'Codystar': 'Codystar:wght@400',
  'Coiny': 'Coiny',
  'Combo': 'Combo',
  'Comic Neue': 'Comic+Neue:wght@400;700',
  'Coming Soon': 'Coming+Soon',
  'Comme': 'Comme:wght@400;500;600;700',
  'Content': 'Content:wght@400;700',
  'Corinthia': 'Corinthia:wght@400;700',
  'Cormorant Infant': 'Cormorant+Infant:wght@400;500;600;700',
  'Cormorant SC': 'Cormorant+SC:wght@400;500;600;700',
  'Cormorant Unicase': 'Cormorant+Unicase:wght@400;500;600;700',
  'Cormorant Upright': 'Cormorant+Upright:wght@400;500;600;700',
  'Covered By Your Grace': 'Covered+By+Your+Grace',
  'Crafty Girls': 'Crafty+Girls',
  'Creepster': 'Creepster',
  'Croissant One': 'Croissant+One',
  'Crushed': 'Crushed',
  'Cute Font': 'Cute+Font',
  'Cutive': 'Cutive',
  'Dai Banna SIL': 'Dai+Banna+SIL:wght@400;500;600;700',
  'Dangrek': 'Dangrek',
  'David Libre': 'David+Libre:wght@400;500;700',
  'Dekko': 'Dekko',
  'Dela Gothic One': 'Dela+Gothic+One',
  'Delicious Handrawn': 'Delicious+Handrawn',
  'Delius Swash Caps': 'Delius+Swash+Caps',
  'Delius Unicase': 'Delius+Unicase:wght@400;700',
  'Della Respira': 'Della+Respira',
  'Denk One': 'Denk+One',
  'Devonshire': 'Devonshire',
  'Dhurjati': 'Dhurjati',
  'Diplomata': 'Diplomata',
  'Diplomata SC': 'Diplomata+SC',
  'Do Hyeon': 'Do+Hyeon',
};

// Extract font family name from CSS font-family string
function extractFontFamily(fontString: string | null | undefined): string | null {
  if (!fontString) return null;
  
  // Get the first font from the comma-separated list
  const firstFont = fontString.split(',')[0].trim();
  
  // Remove quotes if present
  const cleanFont = firstFont.replace(/['"]/g, '');
  
  return cleanFont;
}

// Track loaded fonts globally to avoid duplicate loads
const loadedFonts = new Set<string>();
let allFontsLoaded = false;

// Load all available fonts (for font picker preview)
export function loadAllFonts() {
  if (typeof window === 'undefined' || allFontsLoaded) return;
  
  const fontsToLoad = Object.keys(GOOGLE_FONTS).filter(f => !loadedFonts.has(f));
  if (fontsToLoad.length === 0) {
    allFontsLoaded = true;
    return;
  }

  // Dynamically import WebFont only on client side
  import('webfontloader').then((WebFont) => {
    // Load fonts in batches to avoid overwhelming the browser
    const batchSize = 50;
    const batches: string[][] = [];
    for (let i = 0; i < fontsToLoad.length; i += batchSize) {
      batches.push(fontsToLoad.slice(i, i + batchSize));
    }

    batches.forEach((batch, index) => {
      setTimeout(() => {
        try {
          WebFont.load({
            google: {
              families: batch.map((f) => GOOGLE_FONTS[f]),
            },
            active: () => {
              batch.forEach((f) => loadedFonts.add(f));
              if (index === batches.length - 1) {
                allFontsLoaded = true;
              }
            },
          });
        } catch (error) {
          console.error('Failed to load Google Fonts batch:', error);
        }
      }, index * 100);
    });
  }).catch((error) => {
    console.error('Failed to load WebFont library:', error);
  });
}

export function useGoogleFonts(headingFont?: string | null, bodyFont?: string | null) {
  const loadedRef = useRef<Set<string>>(new Set());

  useEffect(() => {
    // Only run on client side
    if (typeof window === 'undefined') {
      return;
    }

    const fontsToLoad: string[] = [];
    const headingFamily = extractFontFamily(headingFont);
    const bodyFamily = extractFontFamily(bodyFont);



    [headingFamily, bodyFamily].forEach((family) => {
      if (family && GOOGLE_FONTS[family] && !loadedFonts.has(family) && !loadedRef.current.has(family)) {
        fontsToLoad.push(family);
        loadedRef.current.add(family);

      } else if (family && !GOOGLE_FONTS[family]) {
        console.warn('[Font Loader] Font not found in GOOGLE_FONTS map:', family);
      }
    });

    if (fontsToLoad.length === 0) {

      return;
    }



    // Dynamically import WebFont only on client side
    import('webfontloader').then((WebFont) => {
      try {
        WebFont.load({
          google: {
            families: fontsToLoad.map((f) => GOOGLE_FONTS[f]),
          },
          active: () => {
            fontsToLoad.forEach((f) => loadedFonts.add(f));
          },
          inactive: () => {
            fontsToLoad.forEach((f) => loadedRef.current.delete(f));
            console.warn('[Font Loader] Failed to load fonts:', fontsToLoad);
          },
        });
      } catch (error) {
        console.error('[Font Loader] Failed to load Google Fonts:', error);
      }
    }).catch((error) => {
      console.error('[Font Loader] Failed to load WebFont library:', error);
    });
  }, [headingFont, bodyFont]);
}


// Helper to generate font entry
const createFont = (name: string, category: 'sans-serif' | 'serif' | 'display' | 'handwriting' | 'monospace' | 'system') => ({
  id: name.toLowerCase().replace(/\s+/g, ''),
  name,
  value: category === 'system' ? 'system-ui, sans-serif' : `${name}, ${category === 'monospace' ? 'monospace' : category === 'serif' ? 'serif' : 'system-ui, sans-serif'}`,
  category,
});

// Available fonts for the font picker (500+ fonts)
export const AVAILABLE_FONTS = [
  // Sans-Serif
  createFont('Inter', 'sans-serif'),
  createFont('Roboto', 'sans-serif'),
  createFont('Poppins', 'sans-serif'),
  createFont('Montserrat', 'sans-serif'),
  createFont('Open Sans', 'sans-serif'),
  createFont('Lato', 'sans-serif'),
  createFont('Nunito', 'sans-serif'),
  createFont('Source Sans Pro', 'sans-serif'),
  createFont('Raleway', 'sans-serif'),
  createFont('Work Sans', 'sans-serif'),
  createFont('DM Sans', 'sans-serif'),
  createFont('Plus Jakarta Sans', 'sans-serif'),
  createFont('Outfit', 'sans-serif'),
  createFont('Manrope', 'sans-serif'),
  createFont('Space Grotesk', 'sans-serif'),
  createFont('Sora', 'sans-serif'),
  createFont('Figtree', 'sans-serif'),
  createFont('Geist', 'sans-serif'),
  createFont('Rubik', 'sans-serif'),
  createFont('Karla', 'sans-serif'),
  createFont('Mulish', 'sans-serif'),
  createFont('Quicksand', 'sans-serif'),
  createFont('Barlow', 'sans-serif'),
  createFont('Josefin Sans', 'sans-serif'),
  createFont('Cabin', 'sans-serif'),
  createFont('Exo 2', 'sans-serif'),
  createFont('Ubuntu', 'sans-serif'),
  createFont('Fira Sans', 'sans-serif'),
  createFont('Archivo', 'sans-serif'),
  createFont('Hind', 'sans-serif'),
  createFont('Asap', 'sans-serif'),
  createFont('Overpass', 'sans-serif'),
  createFont('Catamaran', 'sans-serif'),
  createFont('Mukta', 'sans-serif'),
  createFont('Heebo', 'sans-serif'),
  createFont('Noto Sans', 'sans-serif'),
  createFont('PT Sans', 'sans-serif'),
  createFont('Titillium Web', 'sans-serif'),
  createFont('Varela Round', 'sans-serif'),
  createFont('Dosis', 'sans-serif'),
  createFont('Oxygen', 'sans-serif'),
  createFont('Questrial', 'sans-serif'),
  createFont('Signika', 'sans-serif'),
  createFont('Prompt', 'sans-serif'),
  createFont('Kanit', 'sans-serif'),
  createFont('Maven Pro', 'sans-serif'),
  createFont('Assistant', 'sans-serif'),
  createFont('Lexend', 'sans-serif'),
  createFont('Red Hat Display', 'sans-serif'),
  createFont('IBM Plex Sans', 'sans-serif'),
  createFont('Urbanist', 'sans-serif'),
  createFont('Jost', 'sans-serif'),
  createFont('Epilogue', 'sans-serif'),
  createFont('Be Vietnam Pro', 'sans-serif'),
  createFont('Readex Pro', 'sans-serif'),
  createFont('Albert Sans', 'sans-serif'),
  createFont('Onest', 'sans-serif'),
  createFont('Bricolage Grotesque', 'sans-serif'),
  createFont('Instrument Sans', 'sans-serif'),
  createFont('Geologica', 'sans-serif'),
  createFont('Schibsted Grotesk', 'sans-serif'),
  createFont('Hanken Grotesk', 'sans-serif'),
  createFont('Nunito Sans', 'sans-serif'),
  createFont('Libre Franklin', 'sans-serif'),
  createFont('Encode Sans', 'sans-serif'),
  createFont('Public Sans', 'sans-serif'),
  createFont('Atkinson Hyperlegible', 'sans-serif'),
  createFont('Lexend Deca', 'sans-serif'),
  createFont('Commissioner', 'sans-serif'),
  createFont('Familjen Grotesk', 'sans-serif'),
  createFont('Kumbh Sans', 'sans-serif'),
  createFont('Syne', 'sans-serif'),
  createFont('Darker Grotesque', 'sans-serif'),
  createFont('Saira', 'sans-serif'),
  createFont('Pathway Extreme', 'sans-serif'),
  createFont('Anybody', 'sans-serif'),
  createFont('Unbounded', 'sans-serif'),
  createFont('Wix Madefor Display', 'sans-serif'),
  createFont('Wix Madefor Text', 'sans-serif'),
  createFont('Gabarito', 'sans-serif'),
  createFont('Funnel Display', 'sans-serif'),
  createFont('Funnel Sans', 'sans-serif'),
  createFont('Afacad', 'sans-serif'),
  createFont('Noto Sans Display', 'sans-serif'),
  createFont('Barlow Condensed', 'sans-serif'),
  createFont('Barlow Semi Condensed', 'sans-serif'),
  createFont('Roboto Condensed', 'sans-serif'),
  createFont('Roboto Flex', 'sans-serif'),
  createFont('Archivo Narrow', 'sans-serif'),
  createFont('Abel', 'sans-serif'),
  createFont('Acme', 'sans-serif'),
  createFont('Advent Pro', 'sans-serif'),
  createFont('Alata', 'sans-serif'),
  createFont('Alegreya Sans', 'sans-serif'),
  createFont('Amaranth', 'sans-serif'),
  createFont('Amiko', 'sans-serif'),
  createFont('Andika', 'sans-serif'),
  createFont('Antonio', 'sans-serif'),
  createFont('Arimo', 'sans-serif'),
  createFont('Armata', 'sans-serif'),
  createFont('Arsenal', 'sans-serif'),
  createFont('Asap Condensed', 'sans-serif'),
  createFont('Average Sans', 'sans-serif'),
  createFont('B612', 'sans-serif'),
  createFont('Balsamiq Sans', 'sans-serif'),
  createFont('Basic', 'sans-serif'),
  createFont('BenchNine', 'sans-serif'),
  createFont('Big Shoulders Display', 'sans-serif'),
  createFont('Big Shoulders Text', 'sans-serif'),
  createFont('Blinker', 'sans-serif'),
  createFont('Cabin Condensed', 'sans-serif'),
  createFont('Cantarell', 'sans-serif'),
  createFont('Capriola', 'sans-serif'),
  createFont('Carme', 'sans-serif'),
  createFont('Carrois Gothic', 'sans-serif'),
  createFont('Chakra Petch', 'sans-serif'),
  createFont('Changa', 'sans-serif'),
  createFont('Chivo', 'sans-serif'),
  createFont('Comfortaa', 'sans-serif'),
  createFont('Convergence', 'sans-serif'),
  createFont('Cuprum', 'sans-serif'),
  createFont('Didact Gothic', 'sans-serif'),
  createFont('Dongle', 'sans-serif'),
  createFont('Doppio One', 'sans-serif'),
  createFont('Economica', 'sans-serif'),
  createFont('El Messiri', 'sans-serif'),
  createFont('Electrolize', 'sans-serif'),
  createFont('Encode Sans Condensed', 'sans-serif'),
  createFont('Encode Sans Expanded', 'sans-serif'),
  createFont('Exo', 'sans-serif'),
  createFont('Expletus Sans', 'sans-serif'),
  createFont('Fahkwang', 'sans-serif'),
  createFont('Fira Sans Condensed', 'sans-serif'),
  createFont('Francois One', 'sans-serif'),
  createFont('Fredoka', 'sans-serif'),
  createFont('Glory', 'sans-serif'),
  createFont('Gothic A1', 'sans-serif'),
  createFont('Gudea', 'sans-serif'),
  createFont('Hammersmith One', 'sans-serif'),
  createFont('Hind Guntur', 'sans-serif'),
  createFont('Hind Madurai', 'sans-serif'),
  createFont('Hind Siliguri', 'sans-serif'),
  createFont('Hind Vadodara', 'sans-serif'),
  createFont('Homenaje', 'sans-serif'),
  createFont('Inria Sans', 'sans-serif'),
  createFont('Inter Tight', 'sans-serif'),
  createFont('Istok Web', 'sans-serif'),
  createFont('Jaldi', 'sans-serif'),
  createFont('Jockey One', 'sans-serif'),
  createFont('Julius Sans One', 'sans-serif'),
  createFont('Jura', 'sans-serif'),
  createFont('K2D', 'sans-serif'),
  createFont('Kantumruy Pro', 'sans-serif'),
  createFont('Khand', 'sans-serif'),
  createFont('Khula', 'sans-serif'),
  createFont('KoHo', 'sans-serif'),
  createFont('Kodchasan', 'sans-serif'),
  createFont('Krub', 'sans-serif'),
  createFont('Kufam', 'sans-serif'),
  createFont('Kulim Park', 'sans-serif'),
  createFont('League Spartan', 'sans-serif'),
  createFont('Livvic', 'sans-serif'),
  createFont('Mada', 'sans-serif'),
  createFont('Magra', 'sans-serif'),
  createFont('Mali', 'sans-serif'),
  createFont('Manjari', 'sans-serif'),
  createFont('Martel Sans', 'sans-serif'),
  createFont('Marvel', 'sans-serif'),
  createFont('Metrophobic', 'sans-serif'),
  createFont('Mina', 'sans-serif'),
  createFont('Mitr', 'sans-serif'),
  createFont('Mohave', 'sans-serif'),
  createFont('Monda', 'sans-serif'),
  createFont('Mouse Memoirs', 'sans-serif'),
  createFont('Mukta Mahee', 'sans-serif'),
  createFont('Mukta Malar', 'sans-serif'),
  createFont('Mukta Vaani', 'sans-serif'),
  createFont('Murecho', 'sans-serif'),
  createFont('News Cycle', 'sans-serif'),
  createFont('Niramit', 'sans-serif'),
  createFont('Nobile', 'sans-serif'),
  createFont('Numans', 'sans-serif'),
  createFont('Offside', 'sans-serif'),
  createFont('Orienta', 'sans-serif'),
  createFont('Overlock', 'sans-serif'),
  createFont('Oxanium', 'sans-serif'),
  createFont('Palanquin', 'sans-serif'),
  createFont('Palanquin Dark', 'sans-serif'),
  createFont('Pangolin', 'sans-serif'),
  createFont('Pathway Gothic One', 'sans-serif'),
  createFont('Pattaya', 'sans-serif'),
  createFont('Pavanam', 'sans-serif'),
  createFont('Philosopher', 'sans-serif'),
  createFont('Play', 'sans-serif'),
  createFont('Pontano Sans', 'sans-serif'),
  createFont('Pragati Narrow', 'sans-serif'),
  createFont('Pridi', 'sans-serif'),
  createFont('Proza Libre', 'sans-serif'),
  createFont('PT Sans Caption', 'sans-serif'),
  createFont('PT Sans Narrow', 'sans-serif'),
  createFont('Puritan', 'sans-serif'),
  createFont('Quantico', 'sans-serif'),
  createFont('Quattrocento Sans', 'sans-serif'),
  createFont('Radio Canada', 'sans-serif'),
  createFont('Rajdhani', 'sans-serif'),
  createFont('Rambla', 'sans-serif'),
  createFont('Rationale', 'sans-serif'),
  createFont('Red Hat Text', 'sans-serif'),
  createFont('Ropa Sans', 'sans-serif'),
  createFont('Rosario', 'sans-serif'),
  createFont('Ruda', 'sans-serif'),
  createFont('Ruluko', 'sans-serif'),
  createFont('Saira Condensed', 'sans-serif'),
  createFont('Saira Extra Condensed', 'sans-serif'),
  createFont('Saira Semi Condensed', 'sans-serif'),
  createFont('Sarabun', 'sans-serif'),
  createFont('Sarala', 'sans-serif'),
  createFont('Sarpanch', 'sans-serif'),
  createFont('Scada', 'sans-serif'),
  createFont('Secular One', 'sans-serif'),
  createFont('Sen', 'sans-serif'),
  createFont('Shanti', 'sans-serif'),
  createFont('Share', 'sans-serif'),
  createFont('Share Tech', 'sans-serif'),
  createFont('Signika Negative', 'sans-serif'),
  createFont('Sintony', 'sans-serif'),
  createFont('Six Caps', 'sans-serif'),
  createFont('Smooch Sans', 'sans-serif'),
  createFont('Sofia Sans', 'sans-serif'),
  createFont('Sofia Sans Condensed', 'sans-serif'),
  createFont('Solway', 'sans-serif'),
  createFont('Sono', 'sans-serif'),
  createFont('Source Sans 3', 'sans-serif'),
  createFont('Spinnaker', 'sans-serif'),
  createFont('Spline Sans', 'sans-serif'),
  createFont('Strait', 'sans-serif'),
  createFont('Sulphur Point', 'sans-serif'),
  createFont('Tajawal', 'sans-serif'),
  createFont('Tauri', 'sans-serif'),
  createFont('Taviraj', 'sans-serif'),
  createFont('Teko', 'sans-serif'),
  createFont('Telex', 'sans-serif'),
  createFont('Tenor Sans', 'sans-serif'),
  createFont('Text Me One', 'sans-serif'),
  createFont('Thasadith', 'sans-serif'),
  createFont('Tomorrow', 'sans-serif'),
  createFont('Trispace', 'sans-serif'),
  createFont('Truculenta', 'sans-serif'),
  createFont('Turret Road', 'sans-serif'),
  createFont('Ubuntu Condensed', 'sans-serif'),
  createFont('Unica One', 'sans-serif'),
  createFont('Varela', 'sans-serif'),
  createFont('Varta', 'sans-serif'),
  createFont('Vazirmatn', 'sans-serif'),
  createFont('Viga', 'sans-serif'),
  createFont('Voltaire', 'sans-serif'),
  createFont('Wire One', 'sans-serif'),
  createFont('Yaldevi', 'sans-serif'),
  createFont('Yantramanav', 'sans-serif'),
  // Serif
  createFont('Playfair Display', 'serif'),
  createFont('Merriweather', 'serif'),
  createFont('Lora', 'serif'),
  createFont('PT Serif', 'serif'),
  createFont('Noto Serif', 'serif'),
  createFont('Libre Baskerville', 'serif'),
  createFont('Crimson Text', 'serif'),
  createFont('Crimson Pro', 'serif'),
  createFont('EB Garamond', 'serif'),
  createFont('Cormorant', 'serif'),
  createFont('Cormorant Garamond', 'serif'),
  createFont('Bitter', 'serif'),
  createFont('Domine', 'serif'),
  createFont('Arvo', 'serif'),
  createFont('Rokkitt', 'serif'),
  createFont('Zilla Slab', 'serif'),
  createFont('Roboto Slab', 'serif'),
  createFont('Roboto Serif', 'serif'),
  createFont('Vollkorn', 'serif'),
  createFont('Spectral', 'serif'),
  createFont('Cardo', 'serif'),
  createFont('Neuton', 'serif'),
  createFont('Old Standard TT', 'serif'),
  createFont('Libre Bodoni', 'serif'),
  createFont('Libre Caslon Text', 'serif'),
  createFont('Literata', 'serif'),
  createFont('Newsreader', 'serif'),
  createFont('Source Serif Pro', 'serif'),
  createFont('Source Serif 4', 'serif'),
  createFont('IBM Plex Serif', 'serif'),
  createFont('DM Serif Display', 'serif'),
  createFont('DM Serif Text', 'serif'),
  createFont('Fraunces', 'serif'),
  createFont('Gelasio', 'serif'),
  createFont('Gentium Plus', 'serif'),
  createFont('Hepta Slab', 'serif'),
  createFont('Ibarra Real Nova', 'serif'),
  createFont('Inria Serif', 'serif'),
  createFont('Josefin Slab', 'serif'),
  createFont('Judson', 'serif'),
  createFont('Karma', 'serif'),
  createFont('Kreon', 'serif'),
  createFont('Laila', 'serif'),
  createFont('Lusitana', 'serif'),
  createFont('Lustria', 'serif'),
  createFont('Manuale', 'serif'),
  createFont('Marcellus', 'serif'),
  createFont('Martel', 'serif'),
  createFont('Mate', 'serif'),
  createFont('Montagu Slab', 'serif'),
  createFont('Noticia Text', 'serif'),
  createFont('Petrona', 'serif'),
  createFont('Piazzolla', 'serif'),
  createFont('Podkova', 'serif'),
  createFont('Prata', 'serif'),
  createFont('Quattrocento', 'serif'),
  createFont('Rasa', 'serif'),
  createFont('Rufina', 'serif'),
  createFont('Sanchez', 'serif'),
  createFont('Slabo 27px', 'serif'),
  createFont('Sorts Mill Goudy', 'serif'),
  createFont('STIX Two Text', 'serif'),
  createFont('Suez One', 'serif'),
  createFont('Sumana', 'serif'),
  createFont('Sura', 'serif'),
  createFont('Texturina', 'serif'),
  createFont('Tienne', 'serif'),
  createFont('Tillana', 'serif'),
  createFont('Tinos', 'serif'),
  createFont('Trirong', 'serif'),
  createFont('Trocchi', 'serif'),
  createFont('Trykker', 'serif'),
  createFont('Unna', 'serif'),
  createFont('Vesper Libre', 'serif'),
  createFont('Viaoda Libre', 'serif'),
  createFont('Vidaloka', 'serif'),
  createFont('Volkhov', 'serif'),
  createFont('Yeseva One', 'serif'),
  createFont('Yrsa', 'serif'),
  createFont('Aleo', 'serif'),
  createFont('Alice', 'serif'),
  createFont('Antic Slab', 'serif'),
  createFont('BioRhyme', 'serif'),
  createFont('Bree Serif', 'serif'),
  createFont('Cantata One', 'serif'),
  createFont('Caudex', 'serif'),
  createFont('Copse', 'serif'),
  createFont('Corben', 'serif'),
  createFont('Crete Round', 'serif'),
  createFont('Eczar', 'serif'),
  createFont('Enriqueta', 'serif'),
  createFont('Faustina', 'serif'),
  createFont('Frank Ruhl Libre', 'serif'),
  createFont('Gilda Display', 'serif'),
  createFont('Glegoo', 'serif'),
  createFont('Halant', 'serif'),
  createFont('Headland One', 'serif'),
  createFont('Inika', 'serif'),
  createFont('Inknut Antiqua', 'serif'),
  createFont('Italiana', 'serif'),
  createFont('Junge', 'serif'),
  createFont('Kameron', 'serif'),
  createFont('Kurale', 'serif'),
  createFont('Ledger', 'serif'),
  createFont('Linden Hill', 'serif'),
  createFont('Maitree', 'serif'),
  createFont('Markazi Text', 'serif'),
  createFont('Oranienbaum', 'serif'),
  createFont('Ovo', 'serif'),
  createFont('Poly', 'serif'),
  createFont('Prociono', 'serif'),
  createFont('Radley', 'serif'),
  createFont('Rosarivo', 'serif'),
  createFont('Rozha One', 'serif'),
  createFont('Sahitya', 'serif'),
  createFont('Scope One', 'serif'),
  createFont('Stoke', 'serif'),
  createFont('Suranna', 'serif'),
  // Display
  createFont('Oswald', 'display'),
  createFont('Bebas Neue', 'display'),
  createFont('Anton', 'display'),
  createFont('Fjalla One', 'display'),
  createFont('Alfa Slab One', 'display'),
  createFont('Archivo Black', 'display'),
  createFont('Bangers', 'display'),
  createFont('Black Ops One', 'display'),
  createFont('Bungee', 'display'),
  createFont('Carter One', 'display'),
  createFont('Changa One', 'display'),
  createFont('Cinzel', 'display'),
  createFont('Cinzel Decorative', 'display'),
  createFont('Concert One', 'display'),
  createFont('Contrail One', 'display'),
  createFont('Fugaz One', 'display'),
  createFont('Graduate', 'display'),
  createFont('Gravitas One', 'display'),
  createFont('Holtwood One SC', 'display'),
  createFont('Krona One', 'display'),
  createFont('League Gothic', 'display'),
  createFont('Lilita One', 'display'),
  createFont('Limelight', 'display'),
  createFont('Lobster', 'display'),
  createFont('Lobster Two', 'display'),
  createFont('Luckiest Guy', 'display'),
  createFont('Monoton', 'display'),
  createFont('Orbitron', 'display'),
  createFont('Pacifico', 'display'),
  createFont('Passion One', 'display'),
  createFont('Patua One', 'display'),
  createFont('Paytone One', 'display'),
  createFont('Permanent Marker', 'display'),
  createFont('Poiret One', 'display'),
  createFont('Press Start 2P', 'display'),
  createFont('Racing Sans One', 'display'),
  createFont('Righteous', 'display'),
  createFont('Russo One', 'display'),
  createFont('Shrikhand', 'display'),
  createFont('Sigmar One', 'display'),
  createFont('Special Elite', 'display'),
  createFont('Squada One', 'display'),
  createFont('Staatliches', 'display'),
  createFont('Titan One', 'display'),
  createFont('Ultra', 'display'),
  createFont('Yanone Kaffeesatz', 'display'),
  createFont('Audiowide', 'display'),
  createFont('Bowlby One SC', 'display'),
  createFont('Calistoga', 'display'),
  createFont('Fredericka the Great', 'display'),
  createFont('Kelly Slab', 'display'),
  createFont('Knewave', 'display'),
  createFont('Leckerli One', 'display'),
  createFont('Megrim', 'display'),
  createFont('Michroma', 'display'),
  createFont('Modak', 'display'),
  createFont('MuseoModerno', 'display'),
  createFont('Oleo Script', 'display'),
  createFont('Original Surfer', 'display'),
  createFont('Pirata One', 'display'),
  createFont('Playball', 'display'),
  createFont('Poller One', 'display'),
  createFont('Rammetto One', 'display'),
  createFont('Ranchers', 'display'),
  createFont('Rowdies', 'display'),
  createFont('Rye', 'display'),
  createFont('Sancreek', 'display'),
  createFont('Shojumaru', 'display'),
  createFont('Skranji', 'display'),
  createFont('Slackey', 'display'),
  createFont('Spicy Rice', 'display'),
  createFont('Stalinist One', 'display'),
  createFont('Stardos Stencil', 'display'),
  createFont('Trade Winds', 'display'),
  createFont('Vast Shadow', 'display'),
  createFont('Wallpoet', 'display'),
  createFont('Warnes', 'display'),
  createFont('Wellfleet', 'display'),
  // Handwriting
  createFont('Dancing Script', 'handwriting'),
  createFont('Caveat', 'handwriting'),
  createFont('Parisienne', 'handwriting'),
  createFont('Great Vibes', 'handwriting'),
  createFont('Satisfy', 'handwriting'),
  createFont('Kaushan Script', 'handwriting'),
  createFont('Sacramento', 'handwriting'),
  createFont('Cookie', 'handwriting'),
  createFont('Courgette', 'handwriting'),
  createFont('Indie Flower', 'handwriting'),
  createFont('Gloria Hallelujah', 'handwriting'),
  createFont('Shadows Into Light', 'handwriting'),
  createFont('Patrick Hand', 'handwriting'),
  createFont('Handlee', 'handwriting'),
  createFont('Amatic SC', 'handwriting'),
  createFont('Yellowtail', 'handwriting'),
  createFont('Tangerine', 'handwriting'),
  createFont('Pinyon Script', 'handwriting'),
  createFont('Alex Brush', 'handwriting'),
  createFont('Allura', 'handwriting'),
  createFont('Bad Script', 'handwriting'),
  createFont('Berkshire Swash', 'handwriting'),
  createFont('Bilbo Swash Caps', 'handwriting'),
  createFont('Cedarville Cursive', 'handwriting'),
  createFont('Clicker Script', 'handwriting'),
  createFont('Damion', 'handwriting'),
  createFont('Dawning of a New Day', 'handwriting'),
  createFont('Delius', 'handwriting'),
  createFont('Euphoria Script', 'handwriting'),
  createFont('Gochi Hand', 'handwriting'),
  createFont('Grand Hotel', 'handwriting'),
  createFont('Homemade Apple', 'handwriting'),
  createFont('Itim', 'handwriting'),
  createFont('Kalam', 'handwriting'),
  createFont('Kristi', 'handwriting'),
  createFont('La Belle Aurore', 'handwriting'),
  createFont('Marck Script', 'handwriting'),
  createFont('Merienda', 'handwriting'),
  createFont('Mr Dafoe', 'handwriting'),
  createFont('Neucha', 'handwriting'),
  createFont('Niconne', 'handwriting'),
  createFont('Nothing You Could Do', 'handwriting'),
  createFont('Over the Rainbow', 'handwriting'),
  createFont('Petit Formal Script', 'handwriting'),
  createFont('Rancho', 'handwriting'),
  createFont('Reenie Beanie', 'handwriting'),
  createFont('Rochester', 'handwriting'),
  createFont('Rock Salt', 'handwriting'),
  createFont('Rouge Script', 'handwriting'),
  createFont('Schoolbell', 'handwriting'),
  createFont('Short Stack', 'handwriting'),
  createFont('Sue Ellen Francisco', 'handwriting'),
  createFont('Waiting for the Sunrise', 'handwriting'),
  createFont('Walter Turncoat', 'handwriting'),
  createFont('Yesteryear', 'handwriting'),
  createFont('Zeyada', 'handwriting'),
  // Monospace
  createFont('Roboto Mono', 'monospace'),
  createFont('Source Code Pro', 'monospace'),
  createFont('Fira Code', 'monospace'),
  createFont('Fira Mono', 'monospace'),
  createFont('JetBrains Mono', 'monospace'),
  createFont('IBM Plex Mono', 'monospace'),
  createFont('Inconsolata', 'monospace'),
  createFont('Space Mono', 'monospace'),
  createFont('Ubuntu Mono', 'monospace'),
  createFont('DM Mono', 'monospace'),
  createFont('Cousine', 'monospace'),
  createFont('Cutive Mono', 'monospace'),
  createFont('Noto Sans Mono', 'monospace'),
  createFont('PT Mono', 'monospace'),
  createFont('Red Hat Mono', 'monospace'),
  createFont('Share Tech Mono', 'monospace'),
  createFont('Spline Sans Mono', 'monospace'),
  createFont('B612 Mono', 'monospace'),
  createFont('Geist Mono', 'monospace'),
  createFont('Oxygen Mono', 'monospace'),
  createFont('Overpass Mono', 'monospace'),
  createFont('Anonymous Pro', 'monospace'),
  createFont('Azeret Mono', 'monospace'),
  createFont('Courier Prime', 'monospace'),
  createFont('Major Mono Display', 'monospace'),
  createFont('Nova Mono', 'monospace'),
  createFont('Syne Mono', 'monospace'),
  createFont('VT323', 'monospace'),
  createFont('Xanh Mono', 'monospace'),
  // System Default
  { id: 'system', name: 'System Default', value: 'system-ui, sans-serif', category: 'system' as const },
];

// Heading-specific fonts (includes display fonts)
export const HEADING_FONTS = AVAILABLE_FONTS;

// Body-specific fonts (excludes display fonts that are hard to read)
export const BODY_FONTS = AVAILABLE_FONTS.filter(f => 
  !['display', 'handwriting'].includes(f.category)
);

// Export font count for reference
export const FONT_COUNT = Object.keys(GOOGLE_FONTS).length;
